---
- name: Debian install sudo packages (apt)
  ansible.builtin.apt:
    name: "{{ sudoers_packages }}"
    state: "present"
    install_recommends: false
    force_apt_get: true
  tags: sudoers

- name: Configure monolith sudoers file (ubuntu)
  ansible.builtin.include_tasks: monolithic_sudoers.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_lsb.major_release|int < 20
  tags: sudoers

- name: Configure sudoers (ubunu)
  ansible.builtin.include_tasks: sudoers.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_lsb.major_release|int >= 20
  tags: sudoers

- name: Configure sudoers (debian)
  ansible.builtin.include_tasks: sudoers.yml
  when:
    - ansible_distribution == "Debian"
    - ansible_lsb.major_release|int >= 12
  tags: sudoers
