---
- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - "vars"
  tags: sudoers

- name: Debug
  ansible.builtin.debug:
    msg: "{{ ansible_os_family }}"
  tags: sudoers

- name: Include tasks debian.yml
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
  tags: sudoers

- name: Include tasks redhat.yml
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: sudoers
