---
- name: Run preflight assertions
  ansible.builtin.include_tasks: preflight.yml
  tags: always

- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution_release'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - "main.yml"
      paths:
        - "vars"
  tags: sudoers

- name: Debug
  ansible.builtin.debug:
    msg: "ansible_distribution: {{ ansible_facts['distribution'] }}"
  tags: sudoers

- name: Include debian.yml
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['distribution'] == 'Debian'
  tags: sudoers

- name: Include ubuntu.yml
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'
  tags: sudoers

- name: Include redhat.yml
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts['distribution'] == 'RedHat'
  tags: sudoers
