---
- name: Prepare
  hosts: all
  become: true

  environment:
    DEBIAN_FRONTEND: "noninteractive"
    TZ: "America/Chicago"

  tasks:
    - name: PREPARE update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
        autoremove: true
        autoclean: true
      changed_when: false
      when: ansible_os_family == 'Debian'
